name: 🚀 CI
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 🔨 Install dependencies
        run: yarn install

      - name: ✨ Lint Project
        run: yarn lint

      - name: 🔨 Build Project
        env:
          MEDIA_HOSTNAME: 'api.notebook-service.com.ua'
          API_URL: 'https://api.notebook-service.com.ua/api'
          NEXT_PUBLIC_MEDIA_URL: 'https://api.notebook-service.com.ua/media'
        run: yarn build
