name: 🚀 CI
on:
  pull_request:
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Lint
        run: npm run lint

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build
