on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    environment: notebook-service-b2b
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 12
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
    
    - name: List output files
      run: find build/ -print
      
    - name: 📂 Sync files
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
        username: 'develop'
        server: 'b2b.notebook-service.com.ua'
        port: 990
        ssh_private_key: ${{ secrets.FTP_KEY }} 
        local_path: './build/*'
        remote_path: 'current/html/'
        args: '-o ConnectTimeout=5'
